version: '3.8'

services:
  server:
    build: ./server
    env_file:
      - ./server/.env
      - ./.env
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    depends_on:
      - mongo

  client:
    build: ./client
    env_file:
      - ./client/.env.development
      - ./.env
    ports:
      - "${PORT_CLIENT}:${PORT_CLIENT}"

  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./microservice/.env
    volumes:
      - ./llm_models:/app/llm_models
    ports:
      - "${PORT_MICROSERVICE}:${PORT_MICROSERVICE}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - "27017:27017"
